language: node_js
node_js:
  - node
  - lts/*
  - 12
  - 12.0.0
  - 11
  - 11.0.0
  - 10
  - 10.0.0
  - 9
  # - 9.0.0 # npm throws: npm ERR! zlib: Cannot read property 'length' of null
  - 8
  - 8.3.0
branches:
  except:
    - /^v[0-9]+(?:\.[0-9]+){1,2}(?:-\S*)?$/
    # Packages not used in Linter and / or test code cannot be tested with CI, so exclude branches of update such packages
    - /^renovate\/can-npm-publish-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/del-cli-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/git-branch-is-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/husky-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/is-git-status-clean-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/lint-staged-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/package-version-git-tag-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/prettier-package-json-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/sort-package-json-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
cache: npm
before_install:
  - npm i -g npm
