language: node_js
node_js:
  - node
  - lts/*
  - 12
  - 12.0.0
  - 11
  - 11.0.0
  - 10
  - 10.0.0
  - 9
  - 9.0.0
  - 8
  - 8.3.0
branches:
  except:
    - /^v[0-9]+(?:\.[0-9]+){1,2}(?:-\S*)?$/
    # Packages not used in Linter and / or test code cannot be tested with CI, so exclude branches of update such packages
    - /^renovate\/can-npm-publish-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/del-cli-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/git-branch-is-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/husky-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/is-git-status-clean-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/lint-staged-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/package-version-git-tag-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/prettier-package-json-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
    - /^renovate\/sort-package-json-[0-9]+(?:\.[0-9])?\.x(?:-lockfile)?$/
cache: npm
sudo: required
before_install:
  # Fixes an issue where the max file watch count is exceeded, triggering ENOSPC
  # see https://github.com/ember-decorators/ember-decorators/commit/8bd65ec0ba4c7bc962434bcc35927f50a47a9db9
  # see https://stackoverflow.com/questions/22475849/node-js-error-enospc#32600959
  # see https://serv-ops.com/knowledge/open.knowledge/view/15
  # see https://www.virment.com/how-to-fix-system-limit-for-number-of-file-watchers-reached/
  #
  # Note: The maximum value for max_user_watches is 524288
  #       see https://qiita.com/neuwell/items/c827c80673de0d787d41
  #
  - sudo sysctl fs.inotify.max_user_watches=524288

  # If npm version is less than 5.10.0, update to 5.10.0
  # see https://qiita.com/ybiquitous/items/dd6cfb03c589452dfdc8#ruby-%E3%82%92%E4%BD%BF%E3%81%862018-06-08
  - |
    if ruby -e "exit(1) if not Gem::Version.new(ARGV[0]) < Gem::Version.new('5.10.0')" $(npm -v); then
      npm i -g npm@5.10.0;
    fi
