# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - template: ./.template/azure-pipelines/jobs/single-test.yml
    parameters:
      jobName: Lint
      steps:
        - label: Run checker
          script: npx --no-install run-s test:readme test:peer-deps test:check-type-defs-pkgs
        - label: Run linter
          script: npx --no-install test-all-peerdeps --skip-rollback run-s lint
          timeoutMin: 60

  - template: ./.template/azure-pipelines/jobs/multi-test.yml
    parameters:
      jobName: UnitTest
      steps:
        - label: Run unit test
          script: npx --no-install test-all-peerdeps --skip-rollback npm run test:ava
          timeoutMin: 60
