parameters:
  nodeVersion: 12.x
  preInstallDeps: {}

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.nodeVersion }}
    displayName: Install Node.js

  - bash: |
      echo node $(node --version)
      echo npm $(npm --version)
    displayName: Show node and npm version

  - ${{ if parameters.preInstallDeps }}:
    script: ${{ format('npm install {0}', parameters.preInstallDeps) }}

  - script: npm ci || npm install
    displayName: Install dependencies
