parameters:
  vmImage: ubuntu-latest
  variables: {}

jobs:
  - job: ${{ parameters.jobName }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    variables: ${{ parameters.variables }}

    steps:
      - template: ../steps/init-node.yml

      - ${{ each stepParams in parameters.steps }}:
          # TODO: Delete later
          - script: |
              node -p 'Object.entries(process.env).filter(([p]) => /^npm_config_cache$/i.test(p)).reduce((o, [p, v]) => ({...o, [p]:v}), {})'
            displayName: Show $npm_config_cache before step

          - script: ${{ stepParams.script }}

            ${{ if stepParams.label }}:
              displayName: ${{ stepParams.label }}

            ${{ if stepParams.timeoutMin }}:
              timeoutInMinutes: ${{ stepParams.timeoutMin }}
            ${{ if not(stepParams.timeoutMin) }}:
              timeoutInMinutes: 5

            ${{ if stepParams.env }}:
              env: ${{ stepParams.env }}

    cancelTimeoutInMinutes: 1
