parameters:
  vmImage: ubuntu-latest
  variables: {}
  timeoutMin: 5
  env: {}

jobs:
  - job: ${{ parameters.jobName }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    variables: ${{ parameters.variables }}

    steps:
      - template: ../steps/init-node.yml

      - ${{ each stepParams in parameters.steps }}:
          - script: ${{ stepParams.script }}
            displayName: ${{ stepParams.label }}
            timeoutInMinutes: ${{ stepParams.timeoutMin }}
            env: ${{ stepParams.env }}

    cancelTimeoutInMinutes: 1
